name: my-better-t-app

services:
  mysql:
    image: mysql
    container_name: my-better-t-app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my-better-t-app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - my-better-t-app_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  my-better-t-app_mysql_data: